# GitHub Actions workflow configuration
# This workflow builds a Maven-based Java project and uploads the JAR artifact.
name: CI

# Trigger workflow on push and pull request events against master branch
# All jobs have repeteated steps, which are: checkout, prepare environment (re usable action)
on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Prepare Action
      uses: ./.github/workflows/prepareAction

    # Build the project with Maven, skipping tests
    - run: mvn -B package -DskipTests --file pom.xml

    # Prepare Artifacts
    - run: |
        mkdir -p build
        cp target/*.jar build/

    # Upload the JAR artifact
    - name: Upload Artifact
    
      uses: actions/upload-artifact@v4
      with:
        name: calculator-app
        path: build/

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Prepare Action
      uses: ./.github/workflows/prepareAction

    # Run Linting
    - name: Run Linting
      run: mvn checkstyle:check

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Prepare Action
      uses: ./.github/workflows/prepareAction

    # Run Tests
    - name: Run Tests
      run: mvn test
